export const GET_ALL_ROOM = 'GET_ALL_ROOM';
export const GET_ALL_ROOM_SUCCESS = 'GET_ALL_ROOM_SUCCESS';
export const GET_ALL_ROOM_FAILED = 'GET_ALL_ROOM_FAILED';

export const CREATE_ROOM = 'CREATE_ROOM';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_FAILED = 'CREATE_ROOM_FAILED';
