// Create Coupon
export const CREATE_COUPON = 'CREATE_COUPON';
export const CREATE_COUPON_SUCCESS = 'CREATE_COUPON_SUCCESS';
export const CREATE_COUPON_FAILED = 'CREATE_COUPON_FAILED';

// Get All Coupons
export const GET_ALL_COUPONS = 'GET_ALL_COUPONS';
export const GET_ALL_COUPONS_SUCCESS = 'GET_ALL_COUPONS_SUCCESS';
export const GET_ALL_COUPONS_FAILED = 'GET_ALL_COUPONS_FAILED';

// Delete Coupon
export const DELETE_COUPON = 'DELETE_COUPON';
export const DELETE_COUPON_SUCCESS = 'DELETE_COUPON_SUCCESS';
export const DELETE_COUPON_FAILED = 'DELETE_COUPON_FAILED';

// Update Coupon
export const UPDATE_COUPON = 'UPDATE_COUPON';
export const UPDATE_COUPON_SUCCESS = 'UPDATE_COUPON_SUCCESS';
export const UPDATE_COUPON_FAILED = 'UPDATE_COUPON_FAILED';