
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        LEAD_ADD_NEW : "LEAD_ADD_NEW",
        CONFIRMATION : "CONFIRMATION",
        ADD_CATEGORY : "ADD_CATEGORY",
        ADD_PRODUCT : "ADD_PRODUCT",
        UPDATE_PRODUCT : "UPDATE_PRODUCT",
        ADD_ROOM : "ADD_ROOM",
        UPDATE_REVIEW : "UPDATE_REVIEW",
        UPDATE_ORDER_STATUS : "UPDATE_ORDER_STATUS",
        UPDATE_COUPON : "UPDATE_COUPON",
        ADD_COUPON : "ADD_COUPON",
        DEFAULT : "",
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
    },
});
